// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	ServiceSpec
	ServiceState
	ServiceCreateRequest
	ServiceCreateResponse
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceStatus int32

const (
	ServiceStatus_Deploying  ServiceStatus = 0
	ServiceStatus_Running    ServiceStatus = 1
	ServiceStatus_Terminated ServiceStatus = 2
	ServiceStatus_Error      ServiceStatus = 3
)

var ServiceStatus_name = map[int32]string{
	0: "Deploying",
	1: "Running",
	2: "Terminated",
	3: "Error",
}
var ServiceStatus_value = map[string]int32{
	"Deploying":  0,
	"Running":    1,
	"Terminated": 2,
	"Error":      3,
}

func (x ServiceStatus) String() string {
	return proto.EnumName(ServiceStatus_name, int32(x))
}
func (ServiceStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServiceSpec struct {
	Name    string                          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image   string                          `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Command []string                        `protobuf:"bytes,3,rep,name=command" json:"command,omitempty"`
	Args    []string                        `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	Options map[string]*google_protobuf.Any `protobuf:"bytes,10,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ServiceSpec) Reset()                    { *m = ServiceSpec{} }
func (m *ServiceSpec) String() string            { return proto.CompactTextString(m) }
func (*ServiceSpec) ProtoMessage()               {}
func (*ServiceSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceSpec) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ServiceSpec) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ServiceSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ServiceSpec) GetOptions() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Options
	}
	return nil
}

type ServiceState struct {
	State        *ServiceState                   `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	StateMessage string                          `protobuf:"bytes,2,opt,name=stateMessage" json:"stateMessage,omitempty"`
	Options      map[string]*google_protobuf.Any `protobuf:"bytes,10,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ServiceState) Reset()                    { *m = ServiceState{} }
func (m *ServiceState) String() string            { return proto.CompactTextString(m) }
func (*ServiceState) ProtoMessage()               {}
func (*ServiceState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceState) GetState() *ServiceState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ServiceState) GetStateMessage() string {
	if m != nil {
		return m.StateMessage
	}
	return ""
}

func (m *ServiceState) GetOptions() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Options
	}
	return nil
}

type ServiceCreateRequest struct {
	Spec *ServiceSpec `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
}

func (m *ServiceCreateRequest) Reset()                    { *m = ServiceCreateRequest{} }
func (m *ServiceCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceCreateRequest) ProtoMessage()               {}
func (*ServiceCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceCreateRequest) GetSpec() *ServiceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type ServiceCreateResponse struct {
	Id   string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Spec *ServiceSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
}

func (m *ServiceCreateResponse) Reset()                    { *m = ServiceCreateResponse{} }
func (m *ServiceCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceCreateResponse) ProtoMessage()               {}
func (*ServiceCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServiceCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceCreateResponse) GetSpec() *ServiceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceSpec)(nil), "modoki.ServiceSpec")
	proto.RegisterType((*ServiceState)(nil), "modoki.ServiceState")
	proto.RegisterType((*ServiceCreateRequest)(nil), "modoki.ServiceCreateRequest")
	proto.RegisterType((*ServiceCreateResponse)(nil), "modoki.ServiceCreateResponse")
	proto.RegisterEnum("modoki.ServiceStatus", ServiceStatus_name, ServiceStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Service service

type ServiceClient interface {
	Create(ctx context.Context, in *ServiceCreateRequest, opts ...grpc.CallOption) (*ServiceCreateResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Create(ctx context.Context, in *ServiceCreateRequest, opts ...grpc.CallOption) (*ServiceCreateResponse, error) {
	out := new(ServiceCreateResponse)
	err := grpc.Invoke(ctx, "/modoki.Service/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	Create(context.Context, *ServiceCreateRequest) (*ServiceCreateResponse, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/modoki.Service/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Create(ctx, req.(*ServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "modoki.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Service_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0xc5, 0x76, 0x3e, 0xc8, 0x24, 0x39, 0x45, 0x43, 0x90, 0x4c, 0x04, 0x52, 0x70, 0x43, 0x74,
	0x85, 0x23, 0x85, 0x06, 0x1d, 0x05, 0xe2, 0x23, 0x74, 0x88, 0xc8, 0x47, 0x45, 0xb7, 0x67, 0x0f,
	0xd6, 0xea, 0xe2, 0x5d, 0xb3, 0x6b, 0x9f, 0xe4, 0x1f, 0x4d, 0xc5, 0x1f, 0x40, 0xbb, 0x6b, 0x43,
	0xce, 0x0a, 0xa2, 0xa3, 0x7b, 0x33, 0xf3, 0xf6, 0xcd, 0x7b, 0x63, 0x19, 0xe6, 0x9a, 0xd4, 0x1d,
	0x4f, 0x29, 0x2e, 0x95, 0xac, 0x24, 0x8e, 0x0a, 0x99, 0xc9, 0x5b, 0xbe, 0x7a, 0x92, 0x4b, 0x99,
	0x1f, 0x69, 0x6b, 0xbb, 0x37, 0xf5, 0xb7, 0x2d, 0x13, 0x8d, 0xa3, 0x44, 0x3f, 0x3d, 0x98, 0x5e,
	0xbb, 0x47, 0xd7, 0x25, 0xa5, 0x88, 0x30, 0x10, 0xac, 0xa0, 0xd0, 0x5b, 0x7b, 0x9b, 0x49, 0x62,
	0x31, 0x2e, 0x61, 0xc8, 0x0b, 0x96, 0x53, 0xe8, 0xdb, 0xa6, 0x2b, 0x30, 0x84, 0x71, 0x2a, 0x8b,
	0x82, 0x89, 0x2c, 0x0c, 0xd6, 0xc1, 0x66, 0x92, 0x74, 0xa5, 0xd1, 0x60, 0x2a, 0xd7, 0xe1, 0xc0,
	0xb6, 0x2d, 0xc6, 0x2b, 0x18, 0xcb, 0xb2, 0xe2, 0x52, 0xe8, 0x10, 0xd6, 0xc1, 0x66, 0xba, 0x5b,
	0xc7, 0xce, 0x5c, 0x7c, 0xb2, 0x3d, 0xfe, 0xec, 0x28, 0x7b, 0x51, 0xa9, 0x26, 0xe9, 0x1e, 0xac,
	0x0e, 0x30, 0x3b, 0x1d, 0xe0, 0x02, 0x82, 0x5b, 0x6a, 0x5a, 0x8b, 0x06, 0xe2, 0x25, 0x0c, 0xef,
	0xd8, 0xb1, 0x76, 0x0e, 0xa7, 0xbb, 0x65, 0xec, 0x02, 0xc7, 0x5d, 0xe0, 0xf8, 0xad, 0x68, 0x12,
	0x47, 0xb9, 0xf2, 0x5f, 0x79, 0xd1, 0x0f, 0x0f, 0x66, 0xdd, 0xde, 0x8a, 0x55, 0x64, 0x04, 0xb4,
	0x01, 0x56, 0xd4, 0x08, 0xf4, 0xcc, 0x99, 0x59, 0xe2, 0x28, 0x18, 0xc1, 0xcc, 0x82, 0x4f, 0xa4,
	0xf5, 0x9f, 0xab, 0xdc, 0xeb, 0xe1, 0xeb, 0x7e, 0xdc, 0xe7, 0xe7, 0x14, 0xff, 0x5b, 0xde, 0x37,
	0xb0, 0x6c, 0xf7, 0xbe, 0x57, 0x64, 0xa2, 0xd0, 0xf7, 0x9a, 0x74, 0x85, 0x2f, 0x60, 0xa0, 0x4b,
	0x4a, 0xdb, 0xd4, 0x8f, 0xce, 0x7c, 0x92, 0xc4, 0x12, 0xa2, 0x03, 0x3c, 0xee, 0x09, 0xe8, 0x52,
	0x0a, 0x4d, 0x78, 0x01, 0x3e, 0xcf, 0x5a, 0x6b, 0x3e, 0xcf, 0x7e, 0x2b, 0xfa, 0xff, 0x50, 0xbc,
	0xfc, 0x08, 0xf3, 0x93, 0x53, 0xd4, 0x1a, 0xe7, 0x30, 0xf9, 0x40, 0xe5, 0x51, 0x36, 0x5c, 0xe4,
	0x8b, 0x07, 0x38, 0x85, 0x71, 0x52, 0x0b, 0x61, 0x0a, 0x0f, 0x2f, 0x00, 0xbe, 0x90, 0x2a, 0xb8,
	0x60, 0x15, 0x65, 0x0b, 0x1f, 0x27, 0x30, 0xdc, 0x2b, 0x25, 0xd5, 0x22, 0xd8, 0x1d, 0x60, 0xdc,
	0xea, 0xe0, 0x1e, 0x46, 0xce, 0x1d, 0x3e, 0xed, 0xed, 0xbd, 0x97, 0x7a, 0xf5, 0xec, 0x2f, 0x53,
	0x17, 0xe9, 0x1d, 0x7c, 0x7d, 0xb8, 0x6d, 0xff, 0xa3, 0x9b, 0x91, 0xbd, 0xe8, 0xcb, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xdf, 0x5a, 0x61, 0x1a, 0x59, 0x03, 0x00, 0x00,
}
