CREATE TABLE tokens (
    seq INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    token VARCHAR(512) NOT NULL UNIQUE,
    owner INTEGER NOT NULL,
    author INTEGER NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE tokens ADD INDEX owner_index(owner);
ALTER TABLE tokens ADD INDEX author_index(author);
