// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package modoki

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AppSpec struct {
	Owner       int32             `protobuf:"varint,1,opt,name=owner" json:"owner,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Domain      string            `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	Image       string            `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Command     []string          `protobuf:"bytes,5,rep,name=command" json:"command,omitempty"`
	Args        []string          `protobuf:"bytes,6,rep,name=args" json:"args,omitempty"`
	Env         map[string]string `protobuf:"bytes,7,rep,name=env" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,10,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels      map[string]string `protobuf:"bytes,11,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AppSpec) Reset()                    { *m = AppSpec{} }
func (m *AppSpec) String() string            { return proto.CompactTextString(m) }
func (*AppSpec) ProtoMessage()               {}
func (*AppSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *AppSpec) GetOwner() int32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *AppSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppSpec) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AppSpec) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *AppSpec) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *AppSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *AppSpec) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *AppSpec) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *AppSpec) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type AppStatus struct {
	Id         string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	State      string                     `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	StartedAt  *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	ExitCode   int32                      `protobuf:"varint,4,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	CreatedAt  *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt  *google_protobuf.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Attributes map[string]string          `protobuf:"bytes,12,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AppStatus) Reset()                    { *m = AppStatus{} }
func (m *AppStatus) String() string            { return proto.CompactTextString(m) }
func (*AppStatus) ProtoMessage()               {}
func (*AppStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *AppStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppStatus) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AppStatus) GetStartedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *AppStatus) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *AppStatus) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *AppStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *AppStatus) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type AppCreateRequest struct {
	Spec *AppSpec `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
}

func (m *AppCreateRequest) Reset()                    { *m = AppCreateRequest{} }
func (m *AppCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*AppCreateRequest) ProtoMessage()               {}
func (*AppCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *AppCreateRequest) GetSpec() *AppSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type AppCreateResponse struct {
	Id   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Spec *AppSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
}

func (m *AppCreateResponse) Reset()                    { *m = AppCreateResponse{} }
func (m *AppCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*AppCreateResponse) ProtoMessage()               {}
func (*AppCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *AppCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppCreateResponse) GetSpec() *AppSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func init() {
	proto.RegisterType((*AppSpec)(nil), "modoki.AppSpec")
	proto.RegisterType((*AppStatus)(nil), "modoki.AppStatus")
	proto.RegisterType((*AppCreateRequest)(nil), "modoki.AppCreateRequest")
	proto.RegisterType((*AppCreateResponse)(nil), "modoki.AppCreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for App service

type AppClient interface {
	Create(ctx context.Context, in *AppCreateRequest, opts ...grpc.CallOption) (*AppCreateResponse, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) Create(ctx context.Context, in *AppCreateRequest, opts ...grpc.CallOption) (*AppCreateResponse, error) {
	out := new(AppCreateResponse)
	err := grpc.Invoke(ctx, "/modoki.App/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for App service

type AppServer interface {
	Create(context.Context, *AppCreateRequest) (*AppCreateResponse, error)
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/modoki.App/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Create(ctx, req.(*AppCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "modoki.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _App_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xd5, 0x66, 0x4d, 0x9b, 0x17, 0x60, 0xc5, 0x42, 0xc8, 0x64, 0x07, 0x42, 0xb9, 0x54,
	0x1c, 0x32, 0xa9, 0x93, 0x80, 0x21, 0x0d, 0x29, 0x1b, 0x93, 0x38, 0x70, 0x0a, 0x9c, 0xb8, 0x4c,
	0x6e, 0x62, 0x2a, 0x6b, 0x8d, 0x6d, 0xe2, 0x97, 0xc2, 0x8e, 0x7c, 0x5a, 0xbe, 0x06, 0x8a, 0x9d,
	0x8c, 0x10, 0x10, 0x53, 0x6f, 0x7e, 0xcf, 0xff, 0xdf, 0xbf, 0xcf, 0xef, 0xbd, 0x06, 0xee, 0x1b,
	0x5e, 0xed, 0x44, 0xce, 0x13, 0x5d, 0x29, 0x54, 0xc4, 0x2f, 0x55, 0xa1, 0xae, 0x45, 0xf4, 0x74,
	0xa3, 0xd4, 0x66, 0xcb, 0x8f, 0x6d, 0x76, 0x5d, 0x7f, 0x39, 0x46, 0x51, 0x72, 0x83, 0xac, 0xd4,
	0x4e, 0xb8, 0xf8, 0xe9, 0xc1, 0x34, 0xd5, 0xfa, 0xa3, 0xe6, 0x39, 0x79, 0x04, 0x13, 0xf5, 0x4d,
	0xf2, 0x8a, 0x8e, 0xe2, 0xd1, 0x72, 0x92, 0xb9, 0x80, 0x10, 0x38, 0x90, 0xac, 0xe4, 0x74, 0x1c,
	0x8f, 0x96, 0x41, 0x66, 0xcf, 0xe4, 0x31, 0xf8, 0x85, 0x2a, 0x99, 0x90, 0xd4, 0xb3, 0xd9, 0x36,
	0x6a, 0x1c, 0x44, 0xc9, 0x36, 0x9c, 0x1e, 0xd8, 0xb4, 0x0b, 0x08, 0x85, 0x69, 0xae, 0xca, 0x92,
	0xc9, 0x82, 0x4e, 0x62, 0x6f, 0x19, 0x64, 0x5d, 0xd8, 0x78, 0xb3, 0x6a, 0x63, 0xa8, 0x6f, 0xd3,
	0xf6, 0x4c, 0x5e, 0x80, 0xc7, 0xe5, 0x8e, 0x4e, 0x63, 0x6f, 0x19, 0xae, 0x68, 0xe2, 0x1e, 0x92,
	0xb4, 0x35, 0x26, 0x97, 0x72, 0x77, 0x29, 0xb1, 0xba, 0xc9, 0x1a, 0x11, 0x39, 0x87, 0x90, 0x49,
	0xa9, 0x90, 0xa1, 0x50, 0xd2, 0x50, 0xb0, 0x4c, 0x3c, 0x64, 0xd2, 0xdf, 0x12, 0xc7, 0xf6, 0x21,
	0x72, 0x02, 0xfe, 0x96, 0xad, 0xf9, 0xd6, 0xd0, 0xd0, 0xe2, 0x47, 0x43, 0xfc, 0x83, 0xbd, 0x75,
	0x64, 0x2b, 0x8d, 0x5e, 0xc2, 0xac, 0xab, 0x84, 0xcc, 0xc1, 0xbb, 0xe6, 0x37, 0xb6, 0x69, 0x41,
	0xd6, 0x1c, 0x9b, 0x36, 0xec, 0xd8, 0xb6, 0xee, 0x7a, 0xe6, 0x82, 0x37, 0xe3, 0xd7, 0xa3, 0xe8,
	0x2d, 0xcc, 0x87, 0xd5, 0xec, 0xc5, 0x9f, 0x42, 0xd8, 0x2b, 0x67, 0x1f, 0x74, 0xf1, 0xc3, 0x83,
	0xa0, 0x79, 0x12, 0x32, 0xac, 0x0d, 0x79, 0x00, 0x63, 0x51, 0xb4, 0xe0, 0x58, 0x14, 0x0d, 0x67,
	0x90, 0xe1, 0x2d, 0x67, 0x03, 0x72, 0x0a, 0x60, 0x90, 0x55, 0xc8, 0x8b, 0x2b, 0x86, 0x76, 0xd6,
	0xe1, 0x2a, 0x4a, 0xdc, 0x4e, 0x25, 0xdd, 0x4e, 0x25, 0x9f, 0xba, 0x9d, 0xca, 0x82, 0x56, 0x9d,
	0x22, 0x39, 0x82, 0x80, 0x7f, 0x17, 0x78, 0x95, 0xab, 0xc2, 0xad, 0xc3, 0x24, 0x9b, 0x35, 0x89,
	0x0b, 0x55, 0x58, 0xdf, 0xbc, 0xe2, 0xac, 0xf5, 0x85, 0xbb, 0x7d, 0x5b, 0x75, 0x8a, 0x0d, 0x5a,
	0xeb, 0xa2, 0x43, 0xc3, 0xbb, 0xd1, 0x56, 0x9d, 0x22, 0x49, 0x01, 0x18, 0x62, 0x25, 0xd6, 0x35,
	0x72, 0x43, 0xef, 0xd9, 0x69, 0x3f, 0xeb, 0x4f, 0xdb, 0xb6, 0x26, 0x49, 0x6f, 0x35, 0x6e, 0xe6,
	0x3d, 0x28, 0x3a, 0x83, 0xc3, 0xc1, 0xf5, 0x5e, 0x33, 0x78, 0x05, 0xf3, 0x54, 0xeb, 0x0b, 0xfb,
	0x98, 0x8c, 0x7f, 0xad, 0xb9, 0x41, 0xf2, 0x1c, 0x0e, 0x8c, 0xe6, 0xb9, 0x35, 0x08, 0x57, 0x87,
	0x83, 0xed, 0xcb, 0xec, 0xe5, 0xe2, 0x3d, 0x3c, 0xec, 0x81, 0x46, 0x2b, 0x69, 0xf8, 0x5f, 0x33,
	0xec, 0x9c, 0xc6, 0xff, 0x71, 0x5a, 0xbd, 0x03, 0x2f, 0xd5, 0x9a, 0x9c, 0x81, 0xef, 0xdc, 0x48,
	0xff, 0x2f, 0xf6, 0x47, 0x65, 0xd1, 0x93, 0x7f, 0xdc, 0xb8, 0x9f, 0x3e, 0x9f, 0x7d, 0x6e, 0xbf,
	0x30, 0x6b, 0xdf, 0xf6, 0xfc, 0xe4, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xf9, 0xc0, 0xa1,
	0x81, 0x04, 0x00, 0x00,
}
