// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package modoki is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	AppSpec
	AppStatus
	AppCreateRequest
	AppCreateResponse
	KubernetesConfig
	YAML
	OperateRequest
	OperateResponse
*/
package modoki

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperateKind int32

const (
	OperateKind_Apply  OperateKind = 0
	OperateKind_Delete OperateKind = 1
)

var OperateKind_name = map[int32]string{
	0: "Apply",
	1: "Delete",
}
var OperateKind_value = map[string]int32{
	"Apply":  0,
	"Delete": 1,
}

func (x OperateKind) String() string {
	return proto.EnumName(OperateKind_name, int32(x))
}
func (OperateKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AppSpec struct {
	Owner       int32             `protobuf:"varint,1,opt,name=owner" json:"owner,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Domain      string            `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	Image       string            `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Command     []string          `protobuf:"bytes,5,rep,name=command" json:"command,omitempty"`
	Args        []string          `protobuf:"bytes,6,rep,name=args" json:"args,omitempty"`
	Env         map[string]string `protobuf:"bytes,7,rep,name=env" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,10,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels      map[string]string `protobuf:"bytes,11,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AppSpec) Reset()                    { *m = AppSpec{} }
func (m *AppSpec) String() string            { return proto.CompactTextString(m) }
func (*AppSpec) ProtoMessage()               {}
func (*AppSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppSpec) GetOwner() int32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *AppSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppSpec) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AppSpec) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *AppSpec) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *AppSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *AppSpec) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *AppSpec) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *AppSpec) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type AppStatus struct {
	Id         string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	State      string                     `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	StartedAt  *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	ExitCode   int32                      `protobuf:"varint,4,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	CreatedAt  *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt  *google_protobuf.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Attributes map[string]string          `protobuf:"bytes,12,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AppStatus) Reset()                    { *m = AppStatus{} }
func (m *AppStatus) String() string            { return proto.CompactTextString(m) }
func (*AppStatus) ProtoMessage()               {}
func (*AppStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppStatus) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AppStatus) GetStartedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *AppStatus) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *AppStatus) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *AppStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *AppStatus) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type AppCreateRequest struct {
	Spec *AppSpec `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
}

func (m *AppCreateRequest) Reset()                    { *m = AppCreateRequest{} }
func (m *AppCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*AppCreateRequest) ProtoMessage()               {}
func (*AppCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppCreateRequest) GetSpec() *AppSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type AppCreateResponse struct {
	Id   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Spec *AppSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
}

func (m *AppCreateResponse) Reset()                    { *m = AppCreateResponse{} }
func (m *AppCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*AppCreateResponse) ProtoMessage()               {}
func (*AppCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AppCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppCreateResponse) GetSpec() *AppSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type KubernetesConfig struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *KubernetesConfig) Reset()                    { *m = KubernetesConfig{} }
func (m *KubernetesConfig) String() string            { return proto.CompactTextString(m) }
func (*KubernetesConfig) ProtoMessage()               {}
func (*KubernetesConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KubernetesConfig) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type YAML struct {
	Config string `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *YAML) Reset()                    { *m = YAML{} }
func (m *YAML) String() string            { return proto.CompactTextString(m) }
func (*YAML) ProtoMessage()               {}
func (*YAML) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *YAML) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type OperateRequest struct {
	Id         string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Kind       OperateKind       `protobuf:"varint,2,opt,name=kind,enum=modoki.OperateKind" json:"kind,omitempty"`
	Performer  int32             `protobuf:"varint,3,opt,name=performer" json:"performer,omitempty"`
	Spec       *AppSpec          `protobuf:"bytes,4,opt,name=spec" json:"spec,omitempty"`
	DeleteYaml *YAML             `protobuf:"bytes,5,opt,name=delete_yaml,json=deleteYaml" json:"delete_yaml,omitempty"`
	ApplyYaml  *YAML             `protobuf:"bytes,6,opt,name=apply_yaml,json=applyYaml" json:"apply_yaml,omitempty"`
	K8SConfig  *KubernetesConfig `protobuf:"bytes,7,opt,name=k8s_config,json=k8sConfig" json:"k8s_config,omitempty"`
}

func (m *OperateRequest) Reset()                    { *m = OperateRequest{} }
func (m *OperateRequest) String() string            { return proto.CompactTextString(m) }
func (*OperateRequest) ProtoMessage()               {}
func (*OperateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OperateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OperateRequest) GetKind() OperateKind {
	if m != nil {
		return m.Kind
	}
	return OperateKind_Apply
}

func (m *OperateRequest) GetPerformer() int32 {
	if m != nil {
		return m.Performer
	}
	return 0
}

func (m *OperateRequest) GetSpec() *AppSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *OperateRequest) GetDeleteYaml() *YAML {
	if m != nil {
		return m.DeleteYaml
	}
	return nil
}

func (m *OperateRequest) GetApplyYaml() *YAML {
	if m != nil {
		return m.ApplyYaml
	}
	return nil
}

func (m *OperateRequest) GetK8SConfig() *KubernetesConfig {
	if m != nil {
		return m.K8SConfig
	}
	return nil
}

type OperateResponse struct {
	DeleteYaml *YAML `protobuf:"bytes,1,opt,name=delete_yaml,json=deleteYaml" json:"delete_yaml,omitempty"`
	ApplyYaml  *YAML `protobuf:"bytes,2,opt,name=apply_yaml,json=applyYaml" json:"apply_yaml,omitempty"`
}

func (m *OperateResponse) Reset()                    { *m = OperateResponse{} }
func (m *OperateResponse) String() string            { return proto.CompactTextString(m) }
func (*OperateResponse) ProtoMessage()               {}
func (*OperateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *OperateResponse) GetDeleteYaml() *YAML {
	if m != nil {
		return m.DeleteYaml
	}
	return nil
}

func (m *OperateResponse) GetApplyYaml() *YAML {
	if m != nil {
		return m.ApplyYaml
	}
	return nil
}

func init() {
	proto.RegisterType((*AppSpec)(nil), "modoki.AppSpec")
	proto.RegisterType((*AppStatus)(nil), "modoki.AppStatus")
	proto.RegisterType((*AppCreateRequest)(nil), "modoki.AppCreateRequest")
	proto.RegisterType((*AppCreateResponse)(nil), "modoki.AppCreateResponse")
	proto.RegisterType((*KubernetesConfig)(nil), "modoki.KubernetesConfig")
	proto.RegisterType((*YAML)(nil), "modoki.YAML")
	proto.RegisterType((*OperateRequest)(nil), "modoki.OperateRequest")
	proto.RegisterType((*OperateResponse)(nil), "modoki.OperateResponse")
	proto.RegisterEnum("modoki.OperateKind", OperateKind_name, OperateKind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for App service

type AppClient interface {
	Create(ctx context.Context, in *AppCreateRequest, opts ...grpc.CallOption) (*AppCreateResponse, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) Create(ctx context.Context, in *AppCreateRequest, opts ...grpc.CallOption) (*AppCreateResponse, error) {
	out := new(AppCreateResponse)
	err := grpc.Invoke(ctx, "/modoki.App/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for App service

type AppServer interface {
	Create(context.Context, *AppCreateRequest) (*AppCreateResponse, error)
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/modoki.App/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Create(ctx, req.(*AppCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "modoki.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _App_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// Client API for Generator service

type GeneratorClient interface {
	Operate(ctx context.Context, in *OperateRequest, opts ...grpc.CallOption) (*OperateResponse, error)
}

type generatorClient struct {
	cc *grpc.ClientConn
}

func NewGeneratorClient(cc *grpc.ClientConn) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) Operate(ctx context.Context, in *OperateRequest, opts ...grpc.CallOption) (*OperateResponse, error) {
	out := new(OperateResponse)
	err := grpc.Invoke(ctx, "/modoki.Generator/Operate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Generator service

type GeneratorServer interface {
	Operate(context.Context, *OperateRequest) (*OperateResponse, error)
}

func RegisterGeneratorServer(s *grpc.Server, srv GeneratorServer) {
	s.RegisterService(&_Generator_serviceDesc, srv)
}

func _Generator_Operate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).Operate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/modoki.Generator/Operate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).Operate(ctx, req.(*OperateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Generator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "modoki.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Operate",
			Handler:    _Generator_Operate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0x7e, 0xdb, 0xb4, 0xe9, 0x72, 0xb2, 0x77, 0x2b, 0x06, 0x8d, 0xd0, 0x21, 0x28, 0x05, 0x89,
	0x6a, 0x88, 0x0c, 0x75, 0x12, 0xfb, 0x90, 0x86, 0x94, 0x7d, 0x68, 0x48, 0x1b, 0x42, 0x0a, 0xdc,
	0x8c, 0x9b, 0xca, 0x4d, 0xbc, 0x2a, 0x6a, 0x62, 0x9b, 0xd8, 0x2d, 0xf4, 0x92, 0x9f, 0xc2, 0xaf,
	0xe3, 0x6f, 0xa0, 0x38, 0x4e, 0x17, 0xb2, 0x69, 0x53, 0xef, 0x7c, 0x8e, 0x9f, 0xe7, 0xe9, 0x73,
	0x3e, 0x9c, 0xc2, 0xff, 0x82, 0xa4, 0xb3, 0x28, 0x20, 0x2e, 0x4f, 0x99, 0x64, 0xc8, 0x4c, 0x58,
	0xc8, 0x26, 0x51, 0xe7, 0xf9, 0x98, 0xb1, 0x71, 0x4c, 0xb6, 0x55, 0x76, 0x34, 0xbd, 0xda, 0x96,
	0x51, 0x42, 0x84, 0xc4, 0x09, 0xcf, 0x81, 0xbd, 0x3f, 0x06, 0xb4, 0x3c, 0xce, 0xbf, 0x70, 0x12,
	0xa0, 0x47, 0xd0, 0x64, 0x3f, 0x28, 0x49, 0x9d, 0x5a, 0xb7, 0xd6, 0x6f, 0xfa, 0x79, 0x80, 0x10,
	0x34, 0x28, 0x4e, 0x88, 0x53, 0xef, 0xd6, 0xfa, 0x96, 0xaf, 0xce, 0x68, 0x03, 0xcc, 0x90, 0x25,
	0x38, 0xa2, 0x8e, 0xa1, 0xb2, 0x3a, 0xca, 0x14, 0xa2, 0x04, 0x8f, 0x89, 0xd3, 0x50, 0xe9, 0x3c,
	0x40, 0x0e, 0xb4, 0x02, 0x96, 0x24, 0x98, 0x86, 0x4e, 0xb3, 0x6b, 0xf4, 0x2d, 0xbf, 0x08, 0x33,
	0x6d, 0x9c, 0x8e, 0x85, 0x63, 0xaa, 0xb4, 0x3a, 0xa3, 0x2d, 0x30, 0x08, 0x9d, 0x39, 0xad, 0xae,
	0xd1, 0xb7, 0x07, 0x8e, 0x9b, 0x17, 0xe2, 0x6a, 0x8f, 0xee, 0x29, 0x9d, 0x9d, 0x52, 0x99, 0xce,
	0xfd, 0x0c, 0x84, 0x8e, 0xc0, 0xc6, 0x94, 0x32, 0x89, 0x65, 0xc4, 0xa8, 0x70, 0x40, 0x71, 0xba,
	0x55, 0x8e, 0x77, 0x0d, 0xc9, 0xb9, 0x65, 0x12, 0xda, 0x01, 0x33, 0xc6, 0x23, 0x12, 0x0b, 0xc7,
	0x56, 0xf4, 0xcd, 0x2a, 0xfd, 0x42, 0xdd, 0xe6, 0x4c, 0x0d, 0xed, 0xbc, 0x87, 0x95, 0xc2, 0x09,
	0x6a, 0x83, 0x31, 0x21, 0x73, 0xd5, 0x34, 0xcb, 0xcf, 0x8e, 0x59, 0x1b, 0x66, 0x38, 0x9e, 0x16,
	0x3d, 0xcb, 0x83, 0x83, 0xfa, 0x5e, 0xad, 0xf3, 0x01, 0xda, 0x55, 0x37, 0x4b, 0xf1, 0xf7, 0xc1,
	0x2e, 0xd9, 0x59, 0x86, 0xda, 0xfb, 0x65, 0x80, 0x95, 0x95, 0x24, 0xb1, 0x9c, 0x0a, 0xb4, 0x06,
	0xf5, 0x28, 0xd4, 0xc4, 0x7a, 0x14, 0x66, 0x3c, 0x21, 0xb1, 0x5c, 0xf0, 0x54, 0x80, 0xf6, 0x01,
	0x84, 0xc4, 0xa9, 0x24, 0xe1, 0x10, 0x4b, 0x35, 0x6b, 0x7b, 0xd0, 0x71, 0xf3, 0x9d, 0x72, 0x8b,
	0x9d, 0x72, 0xbf, 0x16, 0x3b, 0xe5, 0x5b, 0x1a, 0xed, 0x49, 0xb4, 0x09, 0x16, 0xf9, 0x19, 0xc9,
	0x61, 0xc0, 0xc2, 0x7c, 0x1d, 0x9a, 0xfe, 0x4a, 0x96, 0x38, 0x66, 0xa1, 0xd2, 0x0d, 0x52, 0x82,
	0xb5, 0x2e, 0xdc, 0xaf, 0xab, 0xd1, 0x9e, 0xcc, 0xa8, 0x53, 0x1e, 0x16, 0x54, 0xfb, 0x7e, 0xaa,
	0x46, 0x7b, 0x12, 0x79, 0x00, 0x58, 0xca, 0x34, 0x1a, 0x4d, 0x25, 0x11, 0xce, 0xaa, 0x9a, 0xf6,
	0x8b, 0xf2, 0xb4, 0x55, 0x6b, 0x5c, 0x6f, 0x81, 0xc9, 0x67, 0x5e, 0x22, 0x75, 0x0e, 0x61, 0xbd,
	0x72, 0xbd, 0xd4, 0x0c, 0x76, 0xa1, 0xed, 0x71, 0x7e, 0xac, 0x8a, 0xf1, 0xc9, 0xf7, 0x29, 0x11,
	0x12, 0xbd, 0x84, 0x86, 0xe0, 0x24, 0x50, 0x02, 0xf6, 0x60, 0xbd, 0xb2, 0x7d, 0xbe, 0xba, 0xec,
	0x7d, 0x84, 0x07, 0x25, 0xa2, 0xe0, 0x8c, 0x0a, 0x72, 0x63, 0x86, 0x85, 0x52, 0xfd, 0x2e, 0xa5,
	0x77, 0xd0, 0x3e, 0x9f, 0x8e, 0x48, 0x4a, 0x89, 0x24, 0xe2, 0x98, 0xd1, 0xab, 0x68, 0x8c, 0x9e,
	0x82, 0x95, 0x3d, 0x6b, 0xc1, 0x71, 0x40, 0xb4, 0xde, 0x75, 0xa2, 0xf7, 0x0c, 0x1a, 0x97, 0xde,
	0xa7, 0x8b, 0xec, 0xd1, 0x07, 0x0a, 0xaf, 0x21, 0x3a, 0xea, 0xfd, 0xae, 0xc3, 0xda, 0x67, 0x4e,
	0xd2, 0x52, 0x4d, 0x55, 0x67, 0xaf, 0xa1, 0x31, 0x89, 0x68, 0xa8, 0x9c, 0xad, 0x0d, 0x1e, 0x16,
	0xce, 0x34, 0xeb, 0x3c, 0xa2, 0xa1, 0xaf, 0x00, 0x99, 0x13, 0x4e, 0xd2, 0x2b, 0x96, 0x26, 0x24,
	0x55, 0xfb, 0xd6, 0xf4, 0xaf, 0x13, 0x8b, 0x02, 0x1b, 0x77, 0x14, 0x88, 0xde, 0x82, 0x1d, 0x92,
	0x98, 0x48, 0x32, 0x9c, 0xe3, 0x24, 0x76, 0x9a, 0x0a, 0xbb, 0x5a, 0x60, 0xb3, 0x4a, 0x7c, 0xc8,
	0x01, 0x97, 0x38, 0x89, 0xd1, 0x1b, 0x00, 0xcc, 0x79, 0x3c, 0xcf, 0xd1, 0xe6, 0x2d, 0x68, 0x4b,
	0xdd, 0x2b, 0xf0, 0x2e, 0xc0, 0x64, 0x4f, 0x0c, 0x75, 0x1b, 0x5a, 0x0a, 0xbc, 0xf8, 0x44, 0x55,
	0xdb, 0xea, 0x5b, 0x93, 0x3d, 0x7d, 0xec, 0x25, 0xb0, 0xbe, 0x68, 0x91, 0x9e, 0x5e, 0xc5, 0x67,
	0x6d, 0x29, 0x9f, 0xf5, 0x3b, 0x7d, 0x6e, 0xbd, 0x02, 0xbb, 0xd4, 0x5b, 0x64, 0x41, 0xd3, 0xcb,
	0xee, 0xda, 0xff, 0x21, 0x00, 0xf3, 0x44, 0x89, 0xb6, 0x6b, 0x83, 0x13, 0x30, 0x3c, 0xce, 0xd1,
	0x21, 0x98, 0xf9, 0x62, 0xa1, 0xf2, 0xd7, 0xf6, 0x9f, 0x25, 0xed, 0x3c, 0xb9, 0xe5, 0x26, 0xaf,
	0x63, 0x70, 0x06, 0xd6, 0x19, 0xa1, 0xd9, 0x8f, 0xb1, 0x14, 0x1d, 0x40, 0x4b, 0xff, 0x30, 0xda,
	0xa8, 0x4c, 0xb9, 0x90, 0x7a, 0x7c, 0x23, 0x9f, 0x0b, 0x1d, 0xad, 0x7c, 0xd3, 0xff, 0x5a, 0x23,
	0x53, 0xbd, 0xe3, 0x9d, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x33, 0x17, 0xfa, 0x98, 0xd5, 0x06,
	0x00, 0x00,
}
